site:
  title: JChunk Docs
  start_page: jchunk::index.adoc

content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: false
  supplemental_files: docs/ui

asciidoc:
  attributes:
    page-pagination: ''

runtime:
  fetch: true

output:
  dir: build/site