package io.jchunk.core.chunk;

/**
 * The Chunk record represents a segment of content with an associated identifier and embedding.
 * This record is used to store information about each chunk generated by the IChunker
 * implementation.
 *
 * @param id the unique identifier for the chunk
 * @param content the actual content of the chunk
 * @author Pablo Sanchidrian Herrera
 */
public record Chunk(int id, String content) {

    public static Chunk of(final int id, final String content) {
        return new Chunk(id, content);
    }
}
